apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: microservices-monorepo-template-by-SUNNY
  title: Microservices DEmo
  description: A Template to setup a sourceloop based monorepo on Github
  tags:
    - sourceloop
    - loopback4
    - backend
    - monorepo
spec:
  owner: backstage/techdocs-core
  type: service
  parameters:
    - title: sunny
      type: object
      properties:
        animal:
          enum:
            - Cat
            - Fish
      allOf:
        - if:
            properties:
              animal:
                const: Cat
          then:
            properties:
              food:
                type: string
                enum:
                  - meat
                  - grass
                  - fish
            required:
              - food
        - if:
            properties:
              animal:
                const: Fish
          then:
            properties:
              food:
                type: string
                enum:
                  - insect
                  - worms
              water:
                type: string
                enum:
                  - lake
                  - sea
            required:
              - food
              - water
        - required:
            - animal
